# Generated by Django 4.2.3 on 2023-08-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userman", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_time_dedication",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_learning_time",
            field=models.CharField(max_length=10),
        ),
    ]
