# Generated by Django 4.2.3 on 2023-08-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userman", "0003_curriculum"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_slug",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="daily_time_dedication",
            field=models.CharField(max_length=10),
        ),
    ]
